config/routes.rb
Receptorcfd::Application.routes.draw do
  devise_for :users

  resources :comprobantes

  
  root :to => 'welcome#index'
  
end

app/models/cfdcsds.rb
class Cfdcsds < ActiveRecord::Base
  attr_accessible :RFC, :edo_certificado, :fec_final_cert, :fec_inicial_cert, :no_serie
end

app/models/cfdfolios.rb
class Cfdfolios < ActiveRecord::Base
  attr_accessible :AnoAprobacion, :FolioFinal, :FolioInicial, :NoAprobacion, :RFC, :Serie
end

app/models/user.rb
class User < ActiveRecord::Base
  
  before_create :set_user_rol
  
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable, :confirmable
         
  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me, :rol
  # attr_accessible :title, :body
  
  # set default rol
  def set_user_rol
  	self.rol = 0
  end
  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/comprobantes_controller.rb
class ComprobantesController < ApplicationController
  
  require 'nokogiri'
  require 'open-uri'
  
  def validate
    
    doc = Nokogiri.XML( "/public/comprobante32.xml" )
    schemata_by_ns = Hash[ doc.root['schemaLocation'].scan(/(\S+)\s+(\S+)/) ]
    schemata_by_ns.each do |ns,xsd_uri|
      xsd = Nokogiri::XML.Schema(open(xsd_uri))
      xsd.validate(doc).each do |error|
        puts error.message
      end
    end
    
  end
  
  # GET /comprobantes
  # GET /comprobantes.json
  def index
    @comprobantes = Comprobante.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @comprobantes }
    end
  end

  # GET /comprobantes/1
  # GET /comprobantes/1.json
  def show
    @comprobante = Comprobante.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @comprobante }
    end
  end

  # GET /comprobantes/new
  # GET /comprobantes/new.json
  def new
    @comprobante = Comprobante.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @comprobante }
    end
  end

  # GET /comprobantes/1/edit
  def edit
    @comprobante = Comprobante.find(params[:id])
  end

  # POST /comprobantes
  # POST /comprobantes.json
  def create
    @comprobante = Comprobante.new(params[:comprobante])

    respond_to do |format|
      if @comprobante.save
        format.html { redirect_to @comprobante, notice: 'Comprobante was successfully created.' }
        format.json { render json: @comprobante, status: :created, location: @comprobante }
      else
        format.html { render action: "new" }
        format.json { render json: @comprobante.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /comprobantes/1
  # PUT /comprobantes/1.json
  def update
    @comprobante = Comprobante.find(params[:id])

    respond_to do |format|
      if @comprobante.update_attributes(params[:comprobante])
        format.html { redirect_to @comprobante, notice: 'Comprobante was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @comprobante.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /comprobantes/1
  # DELETE /comprobantes/1.json
  def destroy
    @comprobante = Comprobante.find(params[:id])
    @comprobante.destroy

    respond_to do |format|
      format.html { redirect_to comprobantes_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper

def alert_type(type)
  case type
    when :alert
      "alert-block"
    when :error
      "alert-error"
    when :notice
      "alert-info"
    when :success
      "alert-success"
    else
      type.to_s
  end
end

end

app/helpers/comprobantes_helper.rb
module ComprobantesHelper
end

app/views/comprobantes/_form.html.erb
<%= form_for @comprobante, :html => { :class => 'form-horizontal' } do |f| %>
  <div class="control-group">
    <%= f.label :uuid, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :uuid, :class => 'text_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :serie, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :serie, :class => 'text_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :folio, :class => 'control-label' %>
    <div class="controls">
      <%= f.number_field :folio, :class => 'number_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :rfcemisor, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_area :rfcemisor, :class => 'text_area' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :rfcreceptor, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_area :rfcreceptor, :class => 'text_area' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :fecha, :class => 'control-label' %>
    <div class="controls">
      <%= f.datetime_select :fecha, :class => 'datetime_select' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :total, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :total, :class => 'text_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :subtotal, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :subtotal, :class => 'text_field' %>
    </div>
  </div>

  <div class="form-actions">
    <%= f.submit nil, :class => 'btn btn-primary' %>
    <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                comprobantes_path, :class => 'btn' %>
  </div>
<% end %>

app/views/comprobantes/edit.html.erb
<%- model_class = Comprobante -%>
<div class="page-header">
  <h1><%=t '.title', :default => t('helpers.titles.edit', :model => model_class.model_name.human,
                                   :default => "Edit #{model_class.model_name.human}") %></h1>
</div>
<%= render :partial => 'form' %>

app/views/comprobantes/index.html.erb
<%- model_class = Comprobante -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.pluralize %></h1>
</div>
<table class="table table-striped">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:id) %></th>
      <th><%= model_class.human_attribute_name(:uuid) %></th>
      <th><%= model_class.human_attribute_name(:serie) %></th>
      <th><%= model_class.human_attribute_name(:folio) %></th>
      <th><%= model_class.human_attribute_name(:rfcemisor) %></th>
      <th><%= model_class.human_attribute_name(:rfcreceptor) %></th>
      <th><%= model_class.human_attribute_name(:fecha) %></th>
      <th><%= model_class.human_attribute_name(:total) %></th>
      <th><%= model_class.human_attribute_name(:subtotal) %></th>
      <th><%= model_class.human_attribute_name(:created_at) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @comprobantes.each do |comprobante| %>
      <tr>
        <td><%= link_to comprobante.id, comprobante_path(comprobante) %></td>
        <td><%= comprobante.uuid %></td>
        <td><%= comprobante.serie %></td>
        <td><%= comprobante.folio %></td>
        <td><%= comprobante.rfcemisor %></td>
        <td><%= comprobante.rfcreceptor %></td>
        <td><%= comprobante.fecha %></td>
        <td><%= comprobante.total %></td>
        <td><%= comprobante.subtotal %></td>
        <td><%=l comprobante.created_at %></td>
        <td>
          <%= link_to t('.edit', :default => t("helpers.links.edit")),
                      edit_comprobante_path(comprobante), :class => 'btn btn-mini' %>
          <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                      comprobante_path(comprobante),
                      :method => :delete,
                      :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                      :class => 'btn btn-mini btn-danger' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to t('.new', :default => t("helpers.links.new")),
            new_comprobante_path,
            :class => 'btn btn-primary' %>

app/views/comprobantes/new.html.erb
<%- model_class = Comprobante -%>
<div class="page-header">
  <h1><%=t '.title', :default => t('helpers.titles.new', :model => model_class.model_name.human,
                                 :default => "New #{model_class.model_name.human}") %></h1>
</div>
<%= render :partial => 'form' %>

app/views/comprobantes/show.html.erb
<%- model_class = Comprobante -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human %></h1>
</div>

<dl class="dl-horizontal">
  <dt><strong><%= model_class.human_attribute_name(:uuid) %>:</strong></dt>
  <dd><%= @comprobante.uuid %></dd>
  <dt><strong><%= model_class.human_attribute_name(:serie) %>:</strong></dt>
  <dd><%= @comprobante.serie %></dd>
  <dt><strong><%= model_class.human_attribute_name(:folio) %>:</strong></dt>
  <dd><%= @comprobante.folio %></dd>
  <dt><strong><%= model_class.human_attribute_name(:rfcemisor) %>:</strong></dt>
  <dd><%= @comprobante.rfcemisor %></dd>
  <dt><strong><%= model_class.human_attribute_name(:rfcreceptor) %>:</strong></dt>
  <dd><%= @comprobante.rfcreceptor %></dd>
  <dt><strong><%= model_class.human_attribute_name(:fecha) %>:</strong></dt>
  <dd><%= @comprobante.fecha %></dd>
  <dt><strong><%= model_class.human_attribute_name(:total) %>:</strong></dt>
  <dd><%= @comprobante.total %></dd>
  <dt><strong><%= model_class.human_attribute_name(:subtotal) %>:</strong></dt>
  <dd><%= @comprobante.subtotal %></dd>
</dl>

<div class="form-actions">
  <%= link_to t('.back', :default => t("helpers.links.back")),
              comprobantes_path, :class => 'btn'  %>
  <%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_comprobante_path(@comprobante), :class => 'btn' %>
  <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              comprobante_path(@comprobante),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
              :class => 'btn btn-danger' %>
</div>

app/views/layouts/application.html copy.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "Receptorcfd" %></title>
    <%= csrf_meta_tags %>

    <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
    <!--[if lt IE 9]>
      <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.6.1/html5shiv.js" type="text/javascript"></script>
    <![endif]-->

    <%= stylesheet_link_tag "application", :media => "all" %>

    <!-- For third-generation iPad with high-resolution Retina display: -->
    <!-- Size should be 144 x 144 pixels -->
    <%= favicon_link_tag 'images/apple-touch-icon-144x144-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '144x144' %>

    <!-- For iPhone with high-resolution Retina display: -->
    <!-- Size should be 114 x 114 pixels -->
    <%= favicon_link_tag 'images/apple-touch-icon-114x114-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '114x114' %>

    <!-- For first- and second-generation iPad: -->
    <!-- Size should be 72 x 72 pixels -->
    <%= favicon_link_tag 'images/apple-touch-icon-72x72-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '72x72' %>

    <!-- For non-Retina iPhone, iPod Touch, and Android 2.1+ devices: -->
    <!-- Size should be 57 x 57 pixels -->
    <%= favicon_link_tag 'images/apple-touch-icon-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png' %>

    <!-- For all other devices -->
    <!-- Size should be 32 x 32 pixels -->
    <%= favicon_link_tag 'favicon.ico', :rel => 'shortcut icon' %>
  </head>
  <body>

    <div class="navbar navbar-fluid-top">
      <div class="navbar-inner">
        <div class="container-fluid">
          <a class="btn btn-navbar" data-target=".nav-collapse" data-toggle="collapse">
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </a>
          <a class="brand" href="#">Receptorcfd</a>
          <div class="container-fluid nav-collapse">
            <ul class="nav">
              <li><%= link_to "Link1", "/path1"  %></li>
              <li><%= link_to "Link2", "/path2"  %></li>
              <li><%= link_to "Link3", "/path3"  %></li>
            </ul>
          </div><!--/.nav-collapse -->
        </div>
      </div>
    </div>

    <div class="container-fluid">
      <div class="row-fluid">
        <div class="span3">
          <div class="well sidebar-nav">
            <ul class="nav nav-list">
              <li class="nav-header">Sidebar</li>
              <li><%= link_to "Link1", "/path1"  %></li>
              <li><%= link_to "Link2", "/path2"  %></li>
              <li><%= link_to "Link3", "/path3"  %></li>
            </ul>
          </div><!--/.well -->
        </div><!--/span-->
        <div class="span9">
          <%= bootstrap_flash %>
          <%= yield %>
        </div>
      </div><!--/row-->

      <footer>
        <p>&copy; Company 2012</p>
      </footer>

    </div> <!-- /container -->

    <!-- Javascripts
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    <%= javascript_include_tag "application" %>

  </body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="es">
  <head>
    <meta charset="utf8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge, chrome=1">
    <meta name="description" content="Receptor y Validador de Facturacion Electronica">
    <meta name="author" content="andres.amaya.diaz@gmail.com">
    <title><%= content_for?(:title) ? yield(:title) : "SoyReceptor.com" %></title>
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag 'bootstrap.css' %>
    <%= stylesheet_link_tag 'bootstrap-responsive.css' %>
    <%= stylesheet_link_tag 'http://fonts.googleapis.com/css?family=Lato:100,300,400,700,900,100italic,300italic,400italic,700italic,900italic' %>
    <%= stylesheet_link_tag 'styles.css' %>
    <%= stylesheet_link_tag 'toastr.css' %>
    
    <!-- <link rel="stylesheet" href="/css/fullcalendar.css"> -->
    
    <%= javascript_include_tag 'http://ajax.googleapis.com/ajax/libs/jquery/1.8.3/jquery.min.js' %>
    <%= javascript_include_tag 'bootstrap.js' %>
    <%= javascript_include_tag 'jquery.knob.js' %>
    <%= javascript_include_tag 'http://d3js.org/d3.v3.min.js' %>
    <%= javascript_include_tag 'jquery.sparkline.min.js' %>
    <%= javascript_include_tag 'toastr.js' %>
    <%= javascript_include_tag 'jquery.tablesorter.min.js' %>
    <%= javascript_include_tag 'jquery.peity.min.js' %>
    
    <!-- <script src="js/fullcalendar.min.js"></script>
    <script src="js/gcal.js"></script>
    <script src="js/setup.js"></script> -->
  </head>
  <body>

  	<%= render partial: "shared/flash_messages", flash: flash %> 
	  
    <div id="in-nav">
      <div class="container">
        <div class="row">
          <div class="span12">
            <ul class="pull-right">
              <li><a href="#">Principal</a></li>
              <li><a href="#">Contacto</a></li>
              <li><a href="logout.html">Salir</a></li>
            </ul><a id="logo" href="index.html">
              <h4>Soy<strong>Receptor</strong>.com</h4></a>
          </div>
        </div>
      </div>
    </div>
    <%= yield %>
    <footer>
      <div class="container">
        <div class="row">
          <div class="span12">
            <p class="pull-right">Politica de Privacidad</p>
            <p>&copy; Copyright 2013 Captiva Tecnologia Digital</p>
          </div>
        </div>
      </div>
    </footer>

    <!-- Javascripts
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    <%= javascript_include_tag "setup" %>

  </body>
</html>

app/views/shared/_flash_messages.html.erb
<% flash.each do |type, message| %>
  <div class="alert <%= alert_type(type) %> fade in">
    <button class="close" data-dismiss="alert">×</button>
    <%= message %>
  </div>
<% end %>

app/views/users/shared/_links.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Ya soy miembro, Entrar", new_session_path(resource_name), { :class => "btn btn-success" } %><br /><br />
<% end -%>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Aun no tienes cuenta? Registrate GRATIS !", new_registration_path(resource_name), { :class => "btn btn-success" } %><br /><br />
<% end -%>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' %>
  <%= link_to "Olvidaste tu password?", new_password_path(resource_name), { :class => "btn btn-info" } %><br /><br />
<% end -%>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "No recibiste el correo de activacion?", new_confirmation_path(resource_name), { :class => "btn btn-info" } %><br /><br />
<% end -%>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br /><br />
<% end -%>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{provider.to_s.titleize}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end -%>
<% end -%>